# Generated by Django 5.0.3 on 2024-07-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatpost',
            name='likes',
            field=models.CharField(default=0, max_length=9000000000),
        ),
    ]
