# Generated by Django 5.0.3 on 2024-07-12 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_creatpost_likes_alter_likepost_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatpost',
            name='likes',
        ),
        migrations.AlterField(
            model_name='likepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usewholiked', to=settings.AUTH_USER_MODEL),
        ),
    ]
